USE [master]
GO

/****** Object:  Database [coba]    Script Date: 31/12/2018 16.56.19 ******/
CREATE DATABASE [coba]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'coba', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.DIMASSQL\MSSQL\DATA\coba.mdf' , SIZE = 819200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'coba_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.DIMASSQL\MSSQL\DATA\coba_log.ldf' , SIZE = 819200KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [coba] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [coba].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [coba] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [coba] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [coba] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [coba] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [coba] SET ARITHABORT OFF 
GO

ALTER DATABASE [coba] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [coba] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [coba] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [coba] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [coba] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [coba] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [coba] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [coba] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [coba] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [coba] SET  DISABLE_BROKER 
GO

ALTER DATABASE [coba] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [coba] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [coba] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [coba] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [coba] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [coba] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [coba] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [coba] SET RECOVERY FULL 
GO

ALTER DATABASE [coba] SET  MULTI_USER 
GO

ALTER DATABASE [coba] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [coba] SET DB_CHAINING OFF 
GO

ALTER DATABASE [coba] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [coba] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [coba] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [coba] SET QUERY_STORE = OFF
GO

ALTER DATABASE [coba] SET  READ_WRITE 
GO

